### ISSUE TITLE
Enabling Proofmode asks if Save can manage and make calls

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#418] opened 2023-03-10 22:41 UTC
In settings, under metadata, if I enable ProofMode a pop-up appears asking me to "Allow _**Save**_ to make and manage phone calls". If you allow that, it then asks to allow _**Save**_  to access photos and media on your device. What is this and why would _**Save**_ need to connect to the phone? Is it in response to the audit findings?

**To Reproduce**
1. Go to Settings
2. Click on Metadata
3. toggle to enable ProofMode
4. See pop-up

**Expected behavior**
It is just unexpected that this happens

**Screenshots**

**Environment (please complete the following information):**
 - OS version: Android 13
 - Device: Samsung Galaxy S10
 - App Version 0.2.5-BETA-5
![poofmode asks for phone access](https://user-images.githubusercontent.com/37166640/224441639-183bc53a-9dff-423f-ac56-b2f8d12c8ad3.jpeg)

**Comment by hiromipaw** [comment] 2023-03-13 14:32
This is a duplicate of: https://github.com/OpenArchive/Save-app-android/issues/337

**Closed as completed** 2023-03-13 14:32 UTC
Labels: bug
