### ISSUE TITLE
On Accessing Save app on next day, the media which are yet to be uploaded are shown as still processing

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#265] opened 2021-11-11 04:26 UTC
On Accessing the Save on next day, the media which are yet to be uploaded (on previous day, we have just selected the media and not uploaded the same) still shows as processing and not getting displayed correctly

**To Reproduce**
1. Go to 'Save App'
2. Click on + icon to select the media
3. Select few media 
4. Without uploading the media, leave the app
5. open the app next and view the media

**Expected behavior**
Media selected on the previous day should be displayed correctly

Actual Result :
On opening the save app on next day, the media keeps processing and nothing is displayed.

**Screenshots**
![Media keeps on processing](https://user-images.githubusercontent.com/8190141/141236760-48893277-5625-415c-8b07-d4959c519809.jpeg)

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: Samsung Galaxy A70
 - App Version : 0.2.4-RC-2

**Comment by johnhess** [comment] 2022-06-14 02:05
@purvi-ranawat can you please verify this is still happening with 0.2.4-RC-5?

**Comment by purvi-ranawat** [comment] 2022-06-15 05:33
@johnhess The issue still exist, I tried with Save 0.2.4-RC.5 on Android 11
attached the screenshot.
![WhatsApp Image 2022-06-15 at 10 58 40 AM](https://user-images.githubusercontent.com/8190141/173746995-a787ea08-2e78-44ce-98ae-3df336b90b0b.jpeg)

**Comment by pkhivesara** [comment] 2022-07-18 00:55
@purvi-ranawat I am still unable to recreate this issue after debugging a bit. I uploaded two images on July 16, 2022 and one image which is queued on July 16 as well. I do see all 3 images as expected when I opened the app today.

Is this issue specific for a certain file type? Are you seeing this issue for videos, audio, images? 

![Image](https://user-images.githubusercontent.com/6237488/179431983-a569d904-6e05-4659-962c-fd730043f453.jpeg)

**Comment by johnhess** [comment] 2022-07-26 14:08
John to replicate/tag

**Comment by johnhess** [comment] 2022-07-26 18:33
Set this up and will check in a day to see how it looks.  Worked fine surviving quits/reboots.

**Comment by johnhess** [comment] 2022-07-27 15:12
I'm also unable to replicate (Samsung Galaxy A21, Android 11, 0.2.4-RC-8).  I'm going to close this as a duplicate of issue #318.

**Closed as completed by johnhess** 2022-07-27 15:12 UTC
Labels: bug, Priority: Medium
