### ISSUE TITLE
Connecting to Guardian Project Nextcloud server not working

### ISSUE THREAD

**Issue by roseregina** [OpenArchive/Save-app-android#212] opened 2020-05-08 22:20 UTC
0.2.3-beta-2
MotoG
GalaxyS7

1. Select "Private Server" on the "Connect Your Space" screen
2. Enter credentials and click check mark to log in
3. Be taken back to Server info page
4. Click arrow in upper left
5. Click "Add a Project" 

**Existing Project**. 
Expected Behaviour:
6. Click "Browse Existing Projects" 
7. A list of all of the existing projects appears
8. Click on desired project
9. Be taken back to the the project screen 
10. Successfully upload files

Actual Behaviour: 
6. Click "Browse Existing Projects" 
7. Taken to screen containing a back arrow in the upper left corner and nothing else, even after waiting more than a minute multiple times
8. Clicking back arrow returns to "Add a project" page
9. No project has been added, so it is not possible to upload files

**New Project** 
Expected Behaviour:  
6. Click "Create a new project" 
7. Prompt for new project name appears
8. Enter project name and click done
9. Add files to be uploaded
10. Files appear uploaded in the the app
11. Files are present in the newly created project folder on the server

Actual Behaviour:  
6. Click "Create a new project" 
7. Prompt for new project name appears
8. Enter project name and click done
9. Add files to be uploaded
10. Files appear in queue but never shows progress
11. Newly created project folder does not appear on the server

**Good Cloud Nextcloud is not having this issue** 
**Even if this is entirely a Nextcloud instance settings problem, it is important to understand for the admin-user documentation for organisations** 

There needs to be some kind of error or something that appears for the user. This is a horrible experience, especially for the first server add in the app.

**Comment by n8fr8** [comment] 2020-05-09 13:51
Please don't include @tladesignz on Android related issues. 

Again, was this with Orbot enabled? Perhaps these are all related to Tor-network latency, and we need to show a new kind of user interface related to network lag/timeout/delays. 

Apologies for the "horrible experience" you are having, and thanks for all the detail.

**Comment by n8fr8** [comment] 2020-05-11 13:56
Just noting here that this is connected to #211 with essentially both issues being related to connecting to Tor/Orbot.

I can confirm that when the connection to Tor via Orbot is up and running, that routing Save uploads over Tor does work. What @roseregina experienced must have either been that Tor was not fully connected itself, or that connecting to Dropbox and NextCloud over Tor was not working. The latter could be caused by hostname not being resolved or the connection being extremely slow.

We can definitely add a few more error messages to handle this:
- "Please check Orbot to make sure it is connected"
- "Connecting to host... please wait..."
- "Error host not found"

I think we have most of these error cases defined on the iOS side, but will just need to ensure we take into account the Tor aspect of it in whatever messages we show.

**Comment by foundscapes** [comment] 2020-05-11 17:41
> Please don't include @tladesignz on Android related issues.
> 
> Again, was this with Orbot enabled? Perhaps these are all related to Tor-network latency, and we need to show a new kind of user interface related to network lag/timeout/delays.
> 
> Apologies for the "horrible experience" you are having, and thanks for all the detail.

@n8fr8 - I added @tladesignz to a few issues since his ios work was winding down and I needed those two things to be finished by now. I'm glad you are able to do it, but we were stuck. I think we have what we need now for Learning Lab so he doesn't have to jump in.

**Comment by roseregina** [comment] 2020-05-11 20:06
I'm fairly sure that I had already force quit orbot before I started this testing because I wanted to make sure the basic functions were working before testing the orbot part. 

This time, I tried to test the behaviour in a variety of configurations, but reached a crash loop where I had to uninstall and reinstall to exit the loop since neither force quitting through Settings > Apps nor restarting the phone broke the cycle. I forwarded you the file from the MotoG and sent you 12 logs from the GalaxyS7, most of which I believe were from trying to open the app (dropped me into the email program immediately on opening **_Save_**, sometimes twice before returning me to the main android screen). I have not yet pinpointed if there is a way to fix the GP cloud connection on either device, but there is an unusably high level of crashing happening on both of the lower end testing phones right now.

**Comment by n8fr8** [comment] 2020-05-15 21:46
@roseregina just to be clear, you are saying there is still a "unusably high level of crashing" with the latest build BETA-3 released 4 days ago?

https://github.com/OpenArchive/Save-app-android/releases/tag/0.2.3-BETA-3

This BETA-3 build specifically addresses all the crash reports you submitted, so I would be hopeful that wasn't the case.

**Comment by foundscapes** [comment] 2020-05-15 21:52
@n8fr8 no, she was testing BETA-2 for this one. We should be listing each version at the top of our reports from now on so there's no confusion. @roseregina

**Comment by foundscapes** [comment] 2020-05-18 22:31
@roseregina please re-test w/ Beta-3, thank you

**Comment by roseregina** [comment] 2020-05-24 23:27
I think that the entire Nextcloud instance is down, given that I cannot log in with either the MotoG or the GalaxyS7 and I get `ERR_CONNECTION_REFUSED` when I try to log in from a desktop browser. Please resolve.

**Comment by foundscapes** [comment] 2020-05-28 19:01
@roseregina do you mean @n8fr8's guardian project nextcloud? Can you test our oa testing one?

**Comment by foundscapes** [comment] 2020-05-28 19:12
I also can no longer connect to the Guardian Project nextcloud server so I will close this issue

**Closed as completed by foundscapes** 2020-05-28 19:12 UTC
Labels: bug
