### ISSUE TITLE
Save App Freezes when Acquire Keys is Clicked after Selecting Internet Archive as a server option

### ISSUE THREAD

**Issue by Ghranty** [OpenArchive/Save-app-android#247] opened 2021-04-16 23:32 UTC
## Prerequisites:

Orbot is enabled

## Case:
Download and install Save by OpenArchive on Playstore, go through splash screens, enable Orbot, select Internet Archive as a server option, then click on Acquire Keys

## Expected result:
Application opens sign in page 

## Actual result:
Application freezes and only responds accordingly after exiting and reopening the app

## Notes:
Reproduced on Huawei Y9s, Android 10 version

Issue moved from [here](https://github.com/OpenArchive/open-archive.org-Website-2019/issues/34)

**Comment by purvi-ranawat** [comment] 2021-05-27 13:51
@foundscapes Able to reproduce the issue on Samsung Galaxy A70 Android 11, by following the above mentioned steps.

**Comment by foundscapes** [comment] 2021-06-10 18:21
@ozgegn can you add the new apk where this should be fixed here? @purvi-ranawat can you test to see if it's fixed?
thank you!

**Comment by purvi-ranawat** [comment] 2021-06-15 10:27
@foundscapes  The issue seems to fixed now as unable to reproduce the same with new apk. Tested on Samsung Galaxy A70, android 11.

**Closed as completed** 2021-06-24 18:00 UTC
Labels: bug
