### ISSUE TITLE
Not allowing me to connect to our Hetzner account

### ISSUE THREAD

**Issue by ceylana** [OpenArchive/Save-app-android#415] opened 2023-02-16 21:39 UTC
**Describe the bug**
App is not letting me log into Hetzner. If I type the wrong password or do not enter the full hetzner server it gives me a login failed warning. However, when all info (server, username, and password) is correct, it just endlessly says "logging in". I've tried logging in to Hetzner with both the /remote.php/webdav included and not included. 

**To Reproduce**
1. Go to Connect your space
2. Click on Private server 
3. Enter login information and click login
4. See endless logging in

**Expected behavior**
Logs into Hetzner. 

**Screenshots**
![signal-2023-02-16-163516](https://user-images.githubusercontent.com/37166640/219492272-e3e111a8-6b64-49de-b030-c48212e80133.jpeg)

**Environment (please complete the following information):**
 - OS version: Android 13
 - Device: Samsung Galaxy S10
 - App Version 0.2.5-BETA-4

**Additional context**
Related to #issues394 https://github.com/OpenArchive/Save-app-android/issues/394

**Comment by hiromipaw** [comment] 2023-02-20 16:12
Duplicate of #394

**Closed as completed by hiromipaw** 2023-02-20 16:12 UTC
Labels: bug
