### ISSUE TITLE
When deleting last media item, doesn't show again until fragment is reloaded

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#497] opened 2023-09-14 17:13 UTC
Note: Known bug: When deleting last media item, doesn't show again until fragment is reloaded. MediaListFragment / MediaGridFragment needs some major refactoring. That stuff is still a mess.

**Comment by foundscapes** [comment] 2023-10-09 22:34
Is this part of the code that is going to be replaced with the ux updates? @tladesignz

**Comment by foundscapes** [comment] 2023-10-12 18:55
@tladesignz I cannot reproduce this, or may not understand what Silvia meant, can you let us know how big of an issue this is and whether or not it will be fixed with the 2.0 design updates? Ty

**Comment by tladesignz** [comment] 2023-10-13 12:16
I am also not sure/don't remember what this meant. I'd say we forget this an concentrate on what QA finds, with the progressed stuff.

**Closed as completed by tladesignz** 2023-10-13 12:16 UTC
Labels: bug, enhancement, Priority: Medium
