### ISSUE TITLE
Implement new images selection flow

### ISSUE THREAD

**Issue by hiromipaw** [OpenArchive/Save-app-android#441] opened 2023-05-26 15:32 UTC
With the new image selection flow images are highlighted when selected (previously only the border would be in green):

![Selected Image](https://github.com/OpenArchive/Save-app-android/assets/1177650/03dfd34a-4dce-4ddd-b9e0-45c7a8a1d7fe)

Once some images are selected the user can add more from the bottom menu or just upload the added media:

![Preview Images](https://github.com/OpenArchive/Save-app-android/assets/1177650/faadb5b0-967d-451b-a1cf-c0bda126ab99)

Clicking on an image allows the user to edit info for that media:

![Preview Images - Instructions](https://github.com/OpenArchive/Save-app-android/assets/1177650/a6a0b75b-8262-4296-b43a-82312e90d731)

If the user decide to upload the medias directly a warning is displayed: 

![Upload - Instructions screen](https://github.com/OpenArchive/Save-app-android/assets/1177650/456c5014-a1c7-4c92-be58-a42cde33680b)

Media information can be edited for multiple of single files by selecting one or more files:
![Preview Media](https://github.com/OpenArchive/Save-app-android/assets/1177650/a7daf643-7016-4801-b483-4c387627f64e)

For single media:
![Single Media Info](https://github.com/OpenArchive/Save-app-android/assets/1177650/cf3c2bd7-3854-4471-aa58-898835855f2f)

For multiple media at once:
![Multi Media Info](https://github.com/OpenArchive/Save-app-android/assets/1177650/23ce5d7b-959b-4e4d-96dc-5b794952732e)

Information is added in a form:
![Adding Info - Instructions](https://github.com/OpenArchive/Save-app-android/assets/1177650/9a1ed7d6-39c1-4e5e-a761-e33ae6f3ebb6)

If back button is pressed a warning is displayed:
![If pressed back](https://github.com/OpenArchive/Save-app-android/assets/1177650/a401fd90-e2e2-4a9e-b10e-2a7bf5cf7e48)

Figma:
https://www.figma.com/file/MngzLdtPsEmvEsUPKsbmE8/Save-App-2.0

**Comment by tladesignz** [comment] 2023-05-30 12:03
First screenshot is from the iOS media picker. Ignore that, we use the system provided stuff!

**Comment by tladesignz** [comment] 2023-10-18 17:17
@purvi-ranawat, this is fixed in 0.3.0-beta3, which I just dropped at the Play Store. Should be available tomorrow.

**Comment by foundscapes** [comment] 2023-10-20 20:35
@tladesignz most of these designs are implemented, although I haven't seen all the popups, are they done too? @purvi-ranawat please test asap. thanks!

**Comment by purvi-ranawat** [comment] 2023-10-21 13:48
@tladesignz / @foundscapes  : I am not able to see the below requirements : 

1) On selecting the image for edit, I am not getting the pop up for Edit Multiples instructions : 



![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/eebb6baa-4bfc-4ecf-92da-12d775f0c92f)

2) When we select multiple images, in the mobile, the total number of images selected is displayed on top left side but in the requirements design, it is not displayed .

Below is the design of the mobile screenshot : 



![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/276ecce2-d065-4524-b492-ecd16bec710a)

3. Also, when we edit the images and click on Back (not pressing Done), I am getting the message stating " the changes will not be saved". But it is appearing only for the first time. When we again go to edit screen and press back without saving the changes, no message is displayed

Rest all the images are fine.

**Comment by tladesignz** [comment] 2023-10-23 11:41
> 1. On selecting the image for edit, I am not getting the pop up for Edit Multiples instructions :

- The popup only ever shows once.
- For me, it shows right after entering the "preview" scene.

I think that's valid behaviour. @foundscapes, if you think it should be different, please advice.

> 2. When we select multiple images, in the mobile, the total number of images selected is displayed on top left side but in the requirements design, it is not displayed .

Since the element already was there, and since we cannot display **all selected media** (could be in the tenths or even hundreds), I thought this display of the number of actually selected items would come in handy to the user as a way to confirm that they are actually doing what they want.

@foundscapes, please advise, when I should remove this or do something else.

> 3. Also, when we edit the images and click on Back (not pressing Done), I am getting the message stating " the changes will not be saved". But it is appearing only for the first time. When we again go to edit screen and press back without saving the changes, no message is displayed

When you select "Got It", it will be marked as shown and never appear again, to not stand in the way of the user.
If you select "cancel", it will appear again, though, the next time you try this.

I believe this is reasonable behaviour, but I can be wrong. No strong opinions about it.
@foundscapes, please advise, if this behaviour should be any different.
Note: We could also make it, so that every change is stored and get rid of the "done" button completely. I actually do believe, that would be the best option.

**Comment by foundscapes** [comment] 2023-10-25 14:46
> > 1. On selecting the image for edit, I am not getting the pop up for Edit Multiples instructions :
> 
>     * The popup only ever shows once.
> 
>     * For me, it shows right after entering the "preview" scene.
> 
> 
> I think that's valid behaviour. @foundscapes, if you think it should be different, please advice.

Don't change, this is expected behavior by design (for the popup to only show upon first use).
> 
> > 2. When we select multiple images, in the mobile, the total number of images selected is displayed on top left side but in the requirements design, it is not displayed .
> 
> Since the element already was there, and since we cannot display **all selected media** (could be in the tenths or even hundreds), I thought this display of the number of actually selected items would come in handy to the user as a way to confirm that they are actually doing what they want.
> 
> @foundscapes, please advise, when I should remove this or do something else.

This is fine to leave in.
> 
> > 3. Also, when we edit the images and click on Back (not pressing Done), I am getting the message stating " the changes will not be saved". But it is appearing only for the first time. When we again go to edit screen and press back without saving the changes, no message is displayed
> 
> When you select "Got It", it will be marked as shown and never appear again, to not stand in the way of the user. If you select "cancel", it will appear again, though, the next time you try this.
> 
> I believe this is reasonable behaviour, but I can be wrong. No strong opinions about it. @foundscapes, please advise, if this behaviour should be any different. Note: We could also make it, so that every change is stored and get rid of the "done" button completely. I actually do believe, that would be the best option.

The issue here is that users need to have confirmation that their edits have saved, regardless of what action they take after (done or back). Please ensure edits are saved regardless of the action after (back/done).

We need to keep the done button bc people were confused about whether edits saved when it was just "back", but we also don't want them to lose edits if they forget and hit the back button (both buttons are necessary).

**Comment by tladesignz** [comment] 2023-10-25 15:19
> The issue here is that users need to have confirmation that their edits have saved, regardless of what action they take after (done or back). Please ensure edits are saved regardless of the action after (back/done.
> 
> We need to keep the done button bc people were confused about whether edits saved when it was just "back", but we also don't want them to lose edits if they forget and hit the back button (both buttons are necessary).

Makes sense!

I'll do the following:
- leave the "Done" button.
- Store changes right away.
- Remove alert about not storing anything when going back without hitting the "Done" button.

**Comment by foundscapes** [comment] 2023-10-25 15:23
Thank you!

**Comment by tladesignz** [comment] 2023-10-26 12:06
@purvi-ranawat, this will be contained in version 0.3.0-beta4 due for release on Friday, 27th.

**Comment by foundscapes** [comment] 2023-10-27 19:29
tested - working in beta4

**Closed as completed by foundscapes** 2023-10-27 19:29 UTC
Labels: Priority: High, UX
