### ISSUE TITLE
Can't change name of server after first entry, but seems like you can

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#190] opened 2020-01-08 23:11 UTC
Save 0.2.2-beta-5 on s7, pixel 3a, or moto-g 

cannot change name of either goodcloud + guardian project spaces after initial setup

**Comment by roseregina** [comment] 2020-01-09 01:50
Save 0.2.2-beta-5

Tested on MotoG

(This refers to the word "Dropbox" where the server name is on other servers and the teal circle with the white letter that is the first letter of the optional server name for other Spaces.) 

Expected: 
Able to click and rename "Dropbox" to something more descriptive

Actual: 
No part of the name can be changed. That screen does not exist or the field on that screen is missing. 

As this stands, it means not only that it's impossible to differentiate between the "sever" icons for different Dropbox, it also means that it looks the same as any server that has been given a name starting with "D".

**Comment by n8fr8** [comment] 2020-04-07 04:12
Fixed ability to change name of WebDAV server.

Having ability to edit "Dropbox" to something more descriptive is a feature, not a bug, and won't fix right now.

**Closed as completed** 2020-05-24 22:14 UTC
Labels: bug, Needs QA
