### ISSUE TITLE
Back button takes back to homepage, not to most recent page

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#77] opened 2018-06-07 21:44 UTC
Tapping the back button on my device always brings me to the ‘home’/’sign in’ screen. Not back to where I just was... I can’t navigate through the app easily.

Tiff tested
Moto G play
OS: Android 6.0.1 
App version: beta-4

**Comment by foundscapes** [comment] 2019-12-05 02:46
@n8fr8 this may no longer be an issue

**Comment by foundscapes** [comment] 2021-03-24 03:00
@ozgegn would you be able to test to make sure this is resolved and then close?

**Comment by purvi-ranawat** [comment] 2021-06-02 08:20
@foundscapes Unable to reproduce the issue on Samsung Galaxy a70 Android 11

**Comment by foundscapes** [comment] 2021-06-10 18:33
@purvi-ranawat great, can you close these issues when they're fixed?

**Comment by purvi-ranawat** [comment] 2021-06-15 10:11
@foundscapes @n8fr8  The issue seems to be fixed now, can close the issue.

**Closed as completed** 2021-06-30 12:00 UTC
Labels: bug
