### ISSUE TITLE
Issue with re-ordering uploads (was Additional files not uploading when adding them to folder that is already uploading)

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#171] opened 2019-12-04 22:40 UTC
phone: Google Pixel 3a
OS: Android 10
Servers: Internet Archive / Good Cloud / NextCloud

Steps:
1. add media to project folder, click upload
2. add more media to same project folder, click upload
3. Expected result: all files will upload
4. Actual result: only files initially added to batch upload, newer additions stall

![AddlItemsNotUploading1](https://user-images.githubusercontent.com/2231711/70187792-ee32ac00-16a3-11ea-8b01-f50dd291b589.png)
![AddlItemsNotUploading](https://user-images.githubusercontent.com/2231711/70187799-effc6f80-16a3-11ea-927d-733f81d637df.png)

The only way they would upload is if I remove them from edit screen and then reupload

**Comment by foundscapes** [comment] 2019-12-04 22:41
Additional question @n8fr8 - do files always upload from last to first? Can we change this to be the other way around / more intuitive? The reordering by size feature is more useful that way.

**Comment by foundscapes** [comment] 2019-12-05 02:10
phone: Moto G
OS: Android 5.1
Server: Good Cloud 

This same thing happened on the MotoG

**Comment by n8fr8** [comment] 2019-12-06 16:05
Fixed in the new release: https://github.com/OpenArchive/Save-app-android/releases/tag/0.2.2-beta-1

**Comment by foundscapes** [comment] 2019-12-06 17:24
Ok will test. Also did you see this? Additional question @n8fr8 - do files always upload from last to first? Can we change this to be the other way around / more intuitive? The reordering by size feature is more useful that way.

**Comment by n8fr8** [comment] 2019-12-06 18:03
Yes, I reproduced it, and completely understand what was happening before.

As for order and re-ordering, still looking into that. Just need to adjust the query being used and how often it is required by the background upload service.

**Comment by foundscapes** [comment] 2019-12-06 18:37
Ok hmm, new problem...semi-order related.

Google Pixel 3a
OS: Android 10
Save v. 0.2.2-beta-1

When I reordered the last item - a video - to be at the top (since files seemed to still be uploading from the bottom) it moved it back to the bottom after I clicked out of edit mode and then stalled at 12% while other file (second to last in queue) began uploading.

![ReorderVidEdit](https://user-images.githubusercontent.com/2231711/70346790-f873b800-1813-11ea-8b76-13233ca763d0.png)
![ReorderVid](https://user-images.githubusercontent.com/2231711/70346805-0295b680-1814-11ea-934a-ecf0558eaa25.png)


There is definitely a random order to upload because after that, another file began uploading higher up, but not the first one. 

![UploadOrder](https://user-images.githubusercontent.com/2231711/70346983-6324f380-1814-11ea-82c8-76f6375c8dc7.png)


The video never fully uploaded and stalled at 12% until the rest were gone. Still stalling 20 mins later

![VidStalled](https://user-images.githubusercontent.com/2231711/70346863-21944880-1814-11ea-9143-e282c683d811.png)

You can see only 5/6 uploaded from main project screen, but the rest went
![NotAllUploadedPreview3a](https://user-images.githubusercontent.com/2231711/70347173-cf075c00-1814-11ea-8e82-1487d1d77f86.png)

**Comment by foundscapes** [comment] 2020-01-24 02:20
Phone: Pixel 3a OS: Android 10 server: oademo (goodcloud)

Added 3 files, began uploading from bottom (order should be from top)
added 4 more files did not crash

**Comment by roseregina** [comment] 2020-01-29 20:11
0.2.2-RC-1

MotoG and GalaxyS7

The app crashes too much of the time when clicking edit to be able to check about successfully changing upload order. 

With both phones, I can only move items up or down one place at a time. I can more a given item more places, but I have to move it slot by slot to do so.

**Comment by n8fr8** [comment] 2020-04-06 21:23
I can't reproduce the crashing anymore. Please test again on the next build. Also implementing better crash reporting so you can more easily share logs.

**Comment by foundscapes** [comment] 2020-04-25 20:18
@roseregina please test with 0.2.3-BETA-1

**Comment by n8fr8** [comment] 2020-06-27 13:55
@purvi-ranawat new build please test: https://github.com/OpenArchive/Save-app-android/releases/tag/0.2.3-RC-1

**Comment by purvi-ranawat** [comment] 2020-07-07 04:51
@n8fr8  / @foundscapes : This is working fine. I am able to move the media up and down anywhere after clicking on edit . It does not crash. Also, while media is uploading , I am also able to add additional media while the current media is uploading and it is uploaded successfully. The app does not crashes. I have tried it on following device :

Android 10 - Samsung A70
Android 5.1.1 - Samsung J3

**Closed as completed** 2021-03-18 18:13 UTC
Labels: bug, Needs QA
