### ISSUE TITLE
Settings page going blank after clicking the back button 

### ISSUE THREAD

**Issue by vanichitkara** [OpenArchive/Save-app-android#462] opened 2023-08-11 16:14 UTC
**Describe the bug**
The settings page goes blank when clicking on the back button when on the main settings page

**To Reproduce**
1. Go to the settings page
2. Click any tab
3. Click the back button to go back to the main settings page
4. Click the back button again
5. A blank screen appears
6. Pressing the back button again at this stage closes the app

**Expected behavior**
Pressing the back button should ideally redirect to the My Media page

**Video with the bug reproduced**
https://github.com/OpenArchive/Save-app-android/assets/64951124/bdf7f3b5-13c1-4bd0-8779-3f490636bb22

**Environment (please complete the following information):**
 - OS version: Android 13
 - Device: Poco X3 Pro
 - App Version: 0.3.0-alpha 4

**Additional context**
The expected behaviour can change depending on how we design the flow of the app, but ideally pressing the back button should take the user to My Media page where they can add folders rather than showing them a blank screen or exiting the app after pressing the back button.

**Comment by tladesignz** [comment] 2023-09-05 16:34
@purvi-ranawat, the fix will be contained in the *upcoming* version 0.3.0-alpha6 build 20535 and later!

**Comment by purvi-ranawat** [comment] 2023-09-12 11:33
@tladesignz : Now, when I go to Settings -> any settings options and then click on back, instead of going to Main Settings screen, it takes me directly to My Media screen

Below is the video : 



https://github.com/OpenArchive/Save-app-android/assets/8190141/79eacacc-470e-485b-b503-40bbbaed2898


Details : 

OS : Android 11, Android 13
Device : Samsung Galaxy A70, Samsung Galaxy A13
App Version : 0.3.0-alpha6

**Comment by uniqx** [comment] 2023-09-29 16:23
fixed by https://github.com/OpenArchive/Save-app-android/commit/9186aabbd61e81bc6a582be5ab1810356c5b314d
will be released with 0.3.0-alpha9

**Comment by foundscapes** [comment] 2023-10-12 18:47
@purvi-ranawat please test, we can't reproduce this problem in beta1, so hope to close. thanks!

**Comment by purvi-ranawat** [comment] 2023-10-13 07:23
This is working fine.

Environment : 
OS : Android11, Android 13
Device : Samsung Galaxy A13, Samsung Galaxy A70
Build Version : 0.3.0-beta1

**Closed as completed** 2023-10-13 12:13 UTC
Labels: bug, Priority: High
