### ISSUE TITLE
Not able to add another dropbox space after adding the first dropbox space on Save App

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#270] opened 2021-11-18 03:21 UTC
Summary : After adding the first dropdown space , user is not able to add another dropdown space as adding another dropdown space option is not there. I am getting the option to add another internet archive or private server space even if we have added one earlier

1. Go to Save App
2. Click on "+" icon to add dropbox space
3. After adding the dropbox space, try to add another dropbox space

Expected Result : 
User should be able to add another dropbox space on save app

Actual Result : 
User is not able to add another dropbox space as no dropbox space option is not there when we click on "+" icon to add another space.

Below is the video link : 

https://drive.google.com/file/d/1JjvczNnww0aTCl9mkc-YJnkB5QzXEQbx/view?usp=sharing

**Environment (please complete the following information):**
 - OS version: Android 11
 - Device: [Samsung Galaxy A70
 - App Version : 0.2.4-RC-2

**Comment by ozgegn** [comment] 2022-02-05 10:50
Hi @purvi-ranawat , @n8fr8 
There is a rule in code that checks if there is any added Dropbox space, it hides the layout for not to add another. Should it be changed ?

**Comment by purvi-ranawat** [comment] 2022-02-15 07:26
@n8fr8  : Can you please reply to the above query from Ozge? I am not sure if this is design requirement that user is able to add only one dropbox. Can you please clarify the same

**Comment by johnhess** [comment] 2022-03-23 20:08
Still able to add just one dropbox space, though I can have several projects within it.

Next steps:
- Do we support multiple spaces in WebDAV/Internet Archive?  If so, how are they differentiated for the user & would same pattern work for drobpox?

**Comment by johnhess** [comment] 2022-06-14 02:06
Oddly, I am now (0.2.4-RC-5) able to add two dropbox spaces _with the same credentials_.  I'd argue that is also a bug in that displaying a duplicate of the same space is not helpful.

**Comment by johnhess** [comment] 2022-09-13 01:26
Let's have our new designer take a look at current state of Dropbox space(s) addition in both apps, the pattern used for webdav in both, and spec out the behavior for that whole set.

**Comment by tladesignz** [comment] 2023-03-15 12:38
One cannot add multiple different Dropbox spaces. That's a limitation of the Dropbox SDK. Sorry.

**Closed as completed by tladesignz** 2023-03-15 12:38 UTC
Labels: bug, design
