### ISSUE TITLE
GoodCloud debugging

### ISSUE THREAD

**Issue by n8fr8** [OpenArchive/Save-app-android#196] opened 2020-01-17 18:25 UTC
Add info here please!

**Comment by foundscapes** [comment] 2020-01-17 18:39
2 issues:

1) So the first issue was that GoodCloud asked user to change the URL seen in the screenshot below to: https://oa.thegood.cloud/remote.php/dav which allowed user to login

![WrongURLPixel2](https://user-images.githubusercontent.com/2231711/72637056-456ba380-3915-11ea-8cf0-4d528744dc09.png)

2) second issue is that once logged in, they could not upload files - they just hung there
![FilesStuck](https://user-images.githubusercontent.com/2231711/72637163-82379a80-3915-11ea-8c44-b61608ec8764.png)
![FilesStuck1](https://user-images.githubusercontent.com/2231711/72637164-82379a80-3915-11ea-97a2-7d1c4b966684.png)

Feedback from GoodCloud (still waiting for user to test):
Hi all, I've been testing with a similar setting and I got the same problem with an account.

What I've done is remove the account from the Save app and added it once again. Be careful with capital letters in the login credentials. In my case there was a difference in login name (with or without capital letter, the app gave no error while connecting  but I wasn't able to upload). After using the exact credentials with Capital letter in the username it worked fine.

I'd also advice to enable Chunking from within Save.

Please let me know if this helped.

**Comment by roseregina** [comment] 2020-05-25 00:20
0.2.3-BETA-3
GalaxyS7 

Still having this problem, plus, now it won't queue files for other servers. It seems to have triggered a crash (after hanging for a while, then recovered and uploaded _all of the files, included the file intended for Good Cloud_ to the other server. I was able to reproduce the uploading to not the intended server without the crash that occurred the first time. 

Is this expected behaviour if no longer logged in to the intended server? If not, I can post a full issue, but I believe that it is separate from the Good Cloud log in problem above.

**Comment by foundscapes** [comment] 2020-05-28 19:18
We need further investigation as files in project folder associated w/ good cloud should not be uploading to a different server (in this case dropbox) @n8fr8 any idea what's going on?

**Comment by n8fr8** [comment] 2020-06-08 20:17
If you had previously asked files to be uploaded to Dropbox, then removed the space/account, there is a chance it could still be in memory uploaded in the background service queue. 

All in all, this is definitely a separate new issue from GoodCloud logging in.

@roseregina when you say "Still having this problem" what is the exact issue, as I don't see any notes from you before. You cannot login to GoodCloud?

**Comment by foundscapes** [comment] 2020-06-08 22:32
@purvi-ranawat can you test this? Let me know if you need clarification

**Comment by foundscapes** [comment] 2021-04-16 22:05
@elric-wamugu can you test this?

**Comment by elric-wamugu** [comment] 2021-04-16 22:31
@foundscapes Yes. Assigning it to myself.

**Comment by elric-wamugu** [comment] 2021-04-20 01:54
@foundscapes Works after logging in with correct credentials. However, it's failing to upload files to folders that have spaces or other special characters in their folder name.

**Comment by purvi-ranawat** [comment] 2021-06-21 16:13
@foundscapes It is working fine now. I tried using the special characters in the folder name and did not face any issue uploading the media.
Tested on Samsung Galaxy A70 Android 11.

**Closed as completed** 2021-06-24 17:54 UTC
Labels: bug, Needs QA, Priority: High
