### ISSUE TITLE
Only "Logging In" is displayed when we enter random characters for Private Server and click on the tick mark

### ISSUE THREAD

**Issue by purvi-ranawat** [OpenArchive/Save-app-android#416] opened 2023-02-28 16:43 UTC
Describe the bug : 
On entering random characters for Private server fields and clicking on tick, only "Logging In" is displayed. Instead proper error message should be displayed to input the correct credentials.

1. Open Save App
2. Click on Private Server
3. Enter random characters in the fields on Private Server Login screen and click on the tick mark to Login

Expected behavior
Error message should be displayed stating to enter the valid credentials

Actual Result : 
Only "Logging in" is displayed

Environment (please complete the following information):
 - OS version: Android 13
 - Device: Samsung Galaxy A32
 - App Version : Save 0.2.5-BETA-5

**Additional context**

**Comment by foundscapes** [comment] 2023-03-07 20:46
I am still having same issue and reproduced this on my phone as well today

    OS version: Android 12
    Device: Google Pixel 3a
    App Version : Save 0.2.5-BETA-5

I'm also getting an infinite loop when trying to login to dropbbox, which was not the case prior, so will make another ticket.

**Comment by tladesignz** [comment] 2023-04-26 09:11
This should be fixed due to the heavy rework on the server transaction part.
I'll do a release today.

Please test then, @purvi-ranawat!

**Comment by purvi-ranawat** [comment] 2023-05-15 09:51
@tladesignz : Now Logging in is not displayed when we enter random characters. But the message " Unable to resolve host. No address asso....." is displayed. The message is not fully displayed. Also, the proper error message stating to enter the valid details should be displayed.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/06ded85e-56dc-421a-af8a-0a5f6e57fd85)

**Comment by tladesignz** [comment] 2023-05-15 13:37
Yeah, yeah, yeah. I know. The limitations of Android-provided "Toasts".
I switched it to a "SnackBar" which shows more text, but not such a nice icon. :-)

Next build which will contain this is 20530.

**Comment by purvi-ranawat** [comment] 2023-08-17 03:19
This is working fine.

Below is the screenshot : 



![Image](https://github.com/OpenArchive/Save-app-android/assets/8190141/1f389fa4-ad2e-48c7-8648-90cc1f7d00b3)

**Closed as completed** 2023-08-25 09:16 UTC
Labels: bug, Priority: Medium
