### ISSUE TITLE
Disconcerting long lag after adding login credentials or trying to switch between servers on many devices

### ISSUE THREAD

**Issue by foundscapes** [OpenArchive/Save-app-android#178] opened 2019-12-17 04:52 UTC
Samsung Galaxy S7
Google Pixeal 3a
Moto G

After hitting either "done" or the checkmark in upper right corner, it can take up to 15 seconds to connect, and often only does if you hit both vs. one or the other.

**Comment by n8fr8** [comment] 2019-12-17 20:12
WebDAV and Dropbox both had the same issue....

**Comment by foundscapes** [comment] 2019-12-17 20:12
need to test on IA

**Comment by n8fr8** [comment] 2019-12-17 20:13
Implement improved UI to indicate that logging in is happening, not stalled/hanging/broken

**Comment by foundscapes** [comment] 2019-12-17 20:17
Not using Tor

**Comment by foundscapes** [comment] 2020-01-06 02:29
0.2.2-beta-3 
s7, 3a, moto-g
This is still happening on all phones

**Comment by foundscapes** [comment] 2020-01-07 19:17
This happens on both GP and GC, will reproduce w/ IA/DrobBox from different /empty login / GC account

**Comment by foundscapes** [comment] 2020-01-08 21:47
Save 0.2.2-beta-5
**Guardian Project Server**

Pixel 3a
1. Login to cloud.guardianproject.info was quick / easy

2. a) Reproduced Samsung 7 Issue by logging in w/ incorrect pw first:
- Expected result: "login failed" popup shows immediately
- Actual result: very long lag (~1min) then "login failed" 

b) tried to login with correct creds and nothing happened at all until backing out and reentering  them

c) removed space from app

d) re-entered correct creds, pressed both check marks multiple times and it logged in with about a 20 second lag


Samsung s7
1. Login to cloud.guardianproject.info lagged over 2 minutes and counting after trying to log in with incorrect pw first BUT backed out of that screen and re-entered all creds and it logged in immediately.

Moto-G

1.  Login to cloud.guardianproject.info was quick / easy
2. a) Reproduced Samsung 7 Issue by logging in w/ incorrect pw first:
- Expected result: "login failed" popup shows immediately
- Actual result: very long lag (~1min) then "login failed" 
b) tried to login with correct creds and nothing happened at all until backing out and reentering  them

c) removed space from app

d) re-entered correct creds, pressed both check marks multiple times and it logged in with about a 20 second lag

**GoodCloud Server**

Pixel 3a
1. Login to oademo.thegood.cloud was quick / easy

2. a) Reproduced Samsung 7 Issue by logging in w/ incorrect pw first:
- Expected result: "login failed" popup shows immediately
- Actual result: shorter lag ~3 seconds then "login failed" popup

b) tried to login with correct creds and nothing happened at all until backing out and reentering  them, waited 2 min 45 seconds and nothing happened still. Did it again and error "login failed" popup showed up within 20 seconds

c) backed out and it took me to goodcloud server space screen even though pw was incorrect - could it be that since we logged in successfully the first time, it didn't override that with the incorrect info? Is that a problem?

d) removed space from app.

e) re-entered correct creds, immediate login successful

Samsung s7
1. Login to oademo.thegood.cloud lagged over 2 minutes and counting after trying to log in with incorrect pw first BUT backed out of that screen and re-entered all creds and it logged in immediately.

Moto-G

1.  Login to oademo.thegood.cloud was quick / easy
2. a) Reproduced Samsung 7 Issue by logging in w/ incorrect pw first:
- Expected result: "login failed" popup shows immediately
- Actual result: very long lag (~1min) then "login failed" 

b) tried to login with correct creds and nothing happened at all until backing out and reentering 

c) re-entered correct creds, pressed both check marks multiple times and it logged in with about a 1 min 30 sec second lag

**Comment by foundscapes** [comment] 2020-01-08 22:46
Save 0.2.2-beta-5
**DropBox** and **Internet Archive** logins were immediate, cannot reproduce issue b/c login is not within **_Save_**

**Comment by roseregina** [comment] 2020-01-09 01:54
**dropbox** 

cannot reproduce exact issue b/c it's not in-app login.

under good cloud server, pixel 3a, step 2c

> c) backed out and it took me to goodcloud server space screen even though pw was incorrect - could it be that since we logged in successfully the first time, it didn't override that with the incorrect info? Is that a problem?

I think that what Natalie wants for behaviour here with Dropbox, is that when you sign in with bad creds, for the existing login/ account token with that server to be deleted, so that you are logged out. Instead, I think that the token stays and continues to work.

**Comment by roseregina** [comment] 2020-01-10 21:07
Save 0.2.2-beta-6
The Good Cloud server
Identical results with MotoG, GalaxyS7, and Pixel3a

expected results:  
1. Enter incorrect login/ password, receive "login failed" error message within ~5 seconds
2. Enter incorrect login/ password, receive "login failed" error message within ~5 seconds
3. Enter correct login/ password, log in and proceed to server screen

actual results: 
1. Enter incorrect login/ password, receive "login failed" error message within ~5 seconds
2. Enter incorrect login/ password, receive no error message after more than 90 seconds (I repeated this step twice, just to make sure)
3. Enter correct login/ password, **received neither advancement to next screen or error message after 90 seconds.** I waited for 5 minutes on the motoG and got no movement. 
4. Go back to add a server screen and click private server
5. Enter correct login/ password, log in and proceed to server screen

**Comment by n8fr8** [comment] 2020-01-10 21:57
I did find one issue in our code that I am fixing.

However, this could also be related to being a security feature against "brute force" attacks. Nextcloud supports throttling and rate limiting to stop attacks on passwords:
https://nextcloud.com/blog/security-in-nextcloud-12-bruteforce-protection-and-rate-limiting-for-developers/

**Comment by n8fr8** [comment] 2020-01-10 22:05
after testing for a bit at home again cloud.guardianproject.info, I received this message on the web login page:

"We have detected multiple invalid login attempts from your IP. Therefore your next login is throttled up to 30 seconds. "

**Comment by n8fr8** [comment] 2020-01-10 22:08
I then added my ip to not be throttled on our server, and the app immediately returns failed from a bad password.

Summary, 1) throttling of bad passwords is a feature not a bug, and 2) there was one small issue in our webdav login code that I am fixing that could have caused login attempts to not be sent after the first try in some cases.

**Comment by roseregina** [comment] 2020-01-10 22:20
Are you saying that the error message from next cloud breaks it or just that it means that it's going to take longer after more than one failed login attempt? 

I'm assuming that it's not worth playing around with until the webdav login code is fixed, but I'm curious to see how this plays out since it seems to me like the rate limiting shouldn't totally break multiple login attempts and I saw this behaviour immediately with the motoG and I hadn't logged in from this IP address for over 24 hours and I waited probably two minutes between the last incorrect password and trying the correct password.

**Comment by foundscapes** [comment] 2020-01-10 23:07
> after testing for a bit at home again cloud.guardianproject.info, I received this message on the web login page:
> 
> "We have detected multiple invalid login attempts from your IP. Therefore your next login is throttled up to 30 seconds. "

Can we make it so after X attempts (more than 3) it locks, but allows people a few tries?

**Comment by foundscapes** [comment] 2020-01-10 23:07
> I did find one issue in our code that I am fixing.
> 
> However, this could also be related to being a security feature against "brute force" attacks. Nextcloud supports throttling and rate limiting to stop attacks on passwords:
> https://nextcloud.com/blog/security-in-nextcloud-12-bruteforce-protection-and-rate-limiting-for-developers/

    
Can we make it so after X attempts (more than 3) it locks, but allows people a few tries?

**Comment by roseregina** [comment] 2020-01-10 23:25
@foundscapes at least some of this is on the server side, so there might be things that can be done in app to help, but ultimately, whoever is running the server gets to decide. 

This is, however, something that should probably go in the documentation for organizations that are going to set up their own next cloud for this, probably along with checking this against the iOS version.

**Comment by n8fr8** [comment] 2020-01-10 23:28
@roseregina the immediate behavior you saw should be fixed now. that was the bug, that after one failed login, it would not work again.

also concurring that this is all server side. we don't have any control on the client about throttling. 

Anyhow, for now, related to logins, this should be fixed as much as we can fix it.

**Comment by foundscapes** [comment] 2020-01-10 23:31
> @foundscapes at least some of this is on the server side, so there might be things that can be done in app to help, but ultimately, whoever is running the server gets to decide.
> 
> This is, however, something that should probably go in the documentation for organizations that are going to set up their own next cloud for this, probably along with checking this against the iOS version.

Yes, once we are finished with android, and I've gotten a good handle on how to set up goodcloud with community partners, I'll write it all up in a user guide!

**Comment by roseregina** [comment] 2020-01-10 23:52
Save 0.2.2-beta-7
The Good Cloud server
Identical results with MotoG, GalaxyS7, and Pixel3a

I tried again with two incorrect attempts, followed by the correct credentials, and all three times were speedy. 

Also, the logging in message is so helpful, and with this version, it was fast enough that it was tricky to get a screen shot of 😍: 
![image](https://user-images.githubusercontent.com/15040203/72194069-16a77780-33c1-11ea-92ff-8d0f320303ef.png)

@n8fr8 is this ticket good to close?

**Comment by n8fr8** [comment] 2020-01-11 00:03
yes!

**Closed as completed by n8fr8** 2020-01-11 00:03 UTC
Labels: bug, Needs QA
